version: "3.8"
services:

  pgdb:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    volumes:
      - ./docker-volumes/pgdb:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mynetwork

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    volumes:
      - ./docker-volumes/pgadmin:/var/lib/pgadmin
    networks:
      - mynetwork
    
    
  gateway:
    build: ./nginx
    container_name: gateway
    ports:
      - "80:80"
    networks:
      - mynetwork
    depends_on:
      - app
  
  app:
    build: .
    depends_on:
      pgdb:
        condition: service_healthy
    environment:
      PORT: 8000
      DB_HOST: pgdb
      DB_PORT: 5432
      DB_USERNAME: admin
      DB_PASSWORD: 1234
      DB_NAME: django101
      PRODUCTION_HOST: app
      GATEWAY_HOST: gateway
    deploy:
      replicas: 3
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
